### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by axaysingh** [shahabvshahabi1996/kickstarter-decentralized-app#1]
how we can deploy it in our browser!

**Comment by shahabvshahabi1996** [comment]
i think it's already deployed on rinkbey test network , 
but first you must register on metamask wallet (google chrome extension) and then open your terminal or cmd and after that you must run : `npm run dev` and i think it must work plz give me feedback

and i'm really sorry that it has no readme file (it's under development) but i'm really sorry i will add it ASAP thanks for your contribution
